### ISSUE TITLE
Enable "show touches"

### ISSUE THREAD

**Issue by messyj232** [JakeWharton/Telecine#102]
"Show touches" is still enabled even though I'm not recording. Please help!!! I have a circle following my finger on the screen!

**Comment by monxalo** [comment]
Unfortunately this happens when for some reason the recorder crashes. A fix was added in the latest version to try to prevent this but if it still doesn't work you can either:

- Go to Development Settings on the Phone and manually disable it
- A quick workaround is to do another recording with `Show Touches` on and the app should disable this when you stop recording.

**Comment by messyj232** [comment]
Thank you!!! :)

**Comment by JakeWharton** [comment]
Yep. Sorry about that. Should be fixed in the latest version!
